" {{{ -- General --
filetype plugin indent on
set autoread
set autoindent
set backspace=indent,eol,start 
set encoding=utf-8
set hidden
set clipboard=unnamedplus
set lazyredraw
set noerrorbells
set noshowmode
set nowrap
set showmatch
set splitright splitbelow
set wildmenu
set wildmode=list:longest,full
set completeopt+=menu,noinsert,popup,fuzzy
runtime macros/matchit.vim

" -- Tab --
set shiftwidth=4
set tabstop=4
set expandtab
set smarttab

" -- Search --
set hlsearch
set incsearch
set ignorecase
set smartcase
" }}}

" {{{ -- Mappings --
let mapleader="\<Space>"

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap j gj
nnoremap k gk

" -- FZF --
nnoremap <leader>a :FzfLua live_grep<CR>
nnoremap <leader>b :FzfLua buffers<CR>
nnoremap <leader>f :FzfLua files<CR>
nnoremap <leader>l :FzfLua lines<CR>
" }}}

" {{{ -- UI --
set number relativenumber       " Display line numbers
set cursorline                  " Highlight current line
set signcolumn=yes
set scrolloff=5                 " Display at least 5 lines around your cursor (for scrolling)
set laststatus=2

colorscheme catppuccin
set background=dark

" -- Languages --

" Filetypes
autocmd BufRead,BufNewFile */.circleci/config.{yaml,yml} set ft=circleci-yaml
autocmd BufRead,BufNewFile Brewfile* set ft=ruby
