#!/usr/bin/env sh

# bar settings
# yabai -m config status_bar                   off
# yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.2
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          3
yabai -m config window_border_radius         6.0
yabai -m config active_window_border_topmost on
yabai -m config active_window_border_color   0xfff5539e
yabai -m config normal_window_border_color   0xff292d3e
# yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.5
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   5

# spaces settings
yabai -m space 1 --label Terminal --layout bsp
yabai -m space 2 --label Browser --layout bsp
yabai -m space 3 --label Misc. --layout float

# application settings
yabai -m rule --add app="^iTerm2$" space=1
yabai -m rule --add app="^kitty$" space=1
yabai -m rule --add app="^Firefox\X*" space=2
yabai -m rule --add app="^System\X*" grid=5:8:2:1:4:3 manage=off

